#This file stores configuration options for Iris, such as the currently active shaderpack
#Tue May 26 07:03:12 MST 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=32
shaderPack=ComplementaryReimagined_r5.8.1 + EuphoriaPatches_1.9.3
enableShaders=true
