name = "Steampunk Wizard City"
author = "Xen Ophelia"
version = "0.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2e73e52f9f8d53ede03e87206e23eb680cec6ec38fac8086681b2e266b3426ef"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
unsup = "1.2.4"

[options]
acceptable-game-versions = []
