name = "Steampunk Wizard City"
author = "Xen Ophelia"
version = "0.3.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e3522e859ccd63cfac4a011b5eef17ab0b1d321c7ebb6f8acbe48478989fedee"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
unsup = "1.2.3"
