name = "Steampunk Wizard City"
author = "Xen Ophelia"
version = "0.3.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6881e8c6aa09e98023bc4722be3078b8e88e6c5d6e630e973becf492f3967a9a"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
