[flavor_groups.visual_quality]
name = "Visual Quality"
description = "How fancy do you want the game to look?"
side = "client"
[[flavor_groups.visual_quality.choices]]
id = "eye_candy"
name = "Eye Candy"
description = "Higher default settings, for all the beauty!\n<ul>Installs:<li>Shaders</li><li>Various small visual upgrades</li><li>Extra UI additions</li></ul>"
[[flavor_groups.visual_quality.choices]]
id = "vr"
name = "Better for VR"
description = "Lower default settings to make VR run smoother, while also keeping visual quality high\n<ul>Installs:<ul><li>Shaders</li><li>Various small visual upgrades</li><li>Extra UI additions</li></ul>"
[[flavor_groups.visual_quality.choices]]
id = "potato"
name = "Potato"
description = "No shaders or extra fancy visual and UI mods.\n<ul><li><b><i>Might</i> improve performance</b> on low-end PC's</li><li>Some UI improvements will still be selected just for QOL</li><li>Will look closer to Vanilla Minecraft</li></ul>"

[flavor_groups.playstyle]
name = "Playstyle"
description = "How will you play?"
side = "client"
[[flavor_groups.playstyle.choices]]
id = "smp"
name = "SMP"
description = "If you <b>only</b> plan to play on multiplayer servers with this modpack installed, choose this"
[[flavor_groups.playstyle.choices]]
id = "singleplayer_worldgen"
name = "Singleplayer Worldgen"
description = "If you also want to create singleplayer worlds with the same world generation mods as a server, choose this"

[metafile.oculus-high]
flavors = ["eye_candy"]
[metafile.oculus-low]
flavors = ["vr"]
[metafile.colorwheel-client]
flavors = ["vr"]
[metafile.complementary-reimagined]
flavors = ["eye_candy", "vr"]
[metafile.sildurs-vibrant-shaders]
flavors = ["eye_candy", "vr"]
[metafile.complementary-reimagined-txt]
flavors = ["eye_candy", "vr"]
[metafile.sildurs-vibrant-shaders-txt]
flavors = ["eye_candy", "vr"]
[metafile.euphoria-patches]
flavors = ["eye_candy", "vr"]
[metafile.supplemental-patches]
flavors = ["eye_candy", "vr"]
[metafile.colorwheel]
flavors = ["eye_candy", "vr"]
[metafile.colorwheel-patcher]
flavors = ["eye_candy", "vr"]
[metafile.chat-heads]
flavors = ["eye_candy", "vr"]
[metafile.farsight]
flavors = ["eye_candy", "vr"]
[metafile.immersivemc]
flavors = ["eye_candy", "vr"]
[metafile.immersive-ui]
flavors = ["eye_candy", "vr"]
[metafile.skin-layers-3d]
flavors = ["eye_candy", "vr"]

[metafile.cristel-lib]
flavors = ["singleplayer_worldgen"]
[metafile.towns-and-towers]
flavors = ["singleplayer_worldgen"]
[metafile.when-dungeons-arise]
flavors = ["singleplayer_worldgen"]
[metafile.when-dungeons-arise-seven-seas]
flavors = ["singleplayer_worldgen"]
[metafile.formations]
flavors = ["singleplayer_worldgen"]
[metafile.formations-nether]
flavors = ["singleplayer_worldgen"]
[metafile.loot-integrations]
flavors = ["singleplayer_worldgen"]
[metafile.loot-integrations-better-archeology]
flavors = ["singleplayer_worldgen"]
[metafile.loot-integrations-born-in-chaos]
flavors = ["singleplayer_worldgen"]
[metafile.loot-integrations-bygone-nether-it-takes-a-pillage]
flavors = ["singleplayer_worldgen"]
[metafile.loot-integrations-formations-overworld-nether]
flavors = ["singleplayer_worldgen"]
[metafile.loot-integrations-integrated-dungeons-villages]
flavors = ["singleplayer_worldgen"]
[metafile.loot-integrations-towns-and-towers]
flavors = ["singleplayer_worldgen"]
[metafile.loot-integrations-when-dungeons-arise]
flavors = ["singleplayer_worldgen"]
[metafile.yung-structures-addon-for-loot-integrations]
flavors = ["singleplayer_worldgen"]
[metafile.repurposed-structures]
flavors = ["singleplayer_worldgen"]
[metafile.tidal-towns]
flavors = ["singleplayer_worldgen"]
[metafile.yungs-better-caves]
flavors = ["singleplayer_worldgen"]
[metafile.yungs-better-desert-temples]
flavors = ["singleplayer_worldgen"]
[metafile.yungs-better-dungeons]
flavors = ["singleplayer_worldgen"]
[metafile.yungs-better-end-island]
flavors = ["singleplayer_worldgen"]
[metafile.yungs-better-jungle-temples]
flavors = ["singleplayer_worldgen"]
[metafile.yungs-better-mineshafts-forge]
flavors = ["singleplayer_worldgen"]
[metafile.yungs-better-nether-fortresses]
flavors = ["singleplayer_worldgen"]
[metafile.yungs-better-ocean-monuments]
flavors = ["singleplayer_worldgen"]
[metafile.yungs-better-strongholds]
flavors = ["singleplayer_worldgen"]
[metafile.yungs-better-witch-huts]
flavors = ["singleplayer_worldgen"]
[metafile.yungs-bridges]
flavors = ["singleplayer_worldgen"]

[metafile.blazeandcaves-advancements-pack]
flavors = ["singleplayer_worldgen"]
[metafile.integrated-villages-configuration]
flavors = ["singleplayer_worldgen"]
[metafile.repurposed-structures-create-dynamic-village]
flavors = ["singleplayer_worldgen"]

[metafile.idas-alexs-mobs]
flavors = ["singleplayer_worldgen"]
[metafile.idas-config]
flavors = ["singleplayer_worldgen"]
[metafile.integrated-stronghold-alexs-mobs-integration]
flavors = ["singleplayer_worldgen"]
[metafile.integrated-stronghold-config]
flavors = ["singleplayer_worldgen"]
[metafile.repurposed-structures-better-desert-temples-compat]
flavors = ["singleplayer_worldgen"]
[metafile.repurposed-structures-better-dungeons-datapack]
flavors = ["singleplayer_worldgen"]
[metafile.repurposed-structures-better-jungle-temples-compat]
flavors = ["singleplayer_worldgen"]
[metafile.repurposed-structures-better-nether-fortress]
flavors = ["singleplayer_worldgen"]
[metafile.repurposed-structures-better-ocean-monuments]
flavors = ["singleplayer_worldgen"]
[metafile.repurposed-structures-better-strongholds-datapack]
flavors = ["singleplayer_worldgen"]
[metafile.repurposed-structures-bygone-nether-compat]
flavors = ["singleplayer_worldgen"]
[metafile.repurposed-structures-domestication-innovation]
flavors = ["singleplayer_worldgen"]
[metafile.repurposed-structures-farmers-delight-datapack]
flavors = ["singleplayer_worldgen"]
[metafile.repurposed-structures-hexerei-datapack-compat]
flavors = ["singleplayer_worldgen"]
[metafile.repurposed-structures-irons-spells-n-spellbooks]
flavors = ["singleplayer_worldgen"]